import type { CaseDefinition } from "@/types/case";

export const seedCases: CaseDefinition[] = [
  {
    metadata: {
      id: "case-001",
      title: "Chest Pain in a 52M",
      specialty: "Cardiology",
      difficulty: "moderate",
      estimatedMinutes: 15,
      tags: ["cardiac", "emergency", "ECG"],
    },
    presentingComplaint:
      "A 52-year-old male presents to the emergency department with substernal chest pain radiating to the left arm, onset 45 minutes ago. He describes it as 'heavy pressure.' He is diaphoretic and anxious.",
    diagnosis: "Acute ST-elevation myocardial infarction (STEMI)",
    clueTree: [
      { id: "c1", text: "Substernal chest pressure radiating to left arm", category: "history", value: 10 },
      { id: "c2", text: "Diaphoresis and anxiety", category: "exam", value: 8 },
      { id: "c3", text: "Onset 45 minutes ago", category: "history", value: 7 },
      { id: "c4", text: "History of hypertension and smoking", category: "history", value: 6 },
      { id: "c5", text: "ST elevation in leads II, III, aVF", category: "labs", value: 10 },
      { id: "c6", text: "Elevated troponin I", category: "labs", value: 9 },
      { id: "c7", text: "Normal chest X-ray", category: "labs", value: 3 },
      { id: "c8", text: "Family history of MI at young age", category: "history", value: 5 },
      { id: "c9", text: "Blood pressure 150/95", category: "exam", value: 4 },
      { id: "c10", text: "Heart rate 105, regular", category: "exam", value: 4 },
    ],
    allowedActions: [
      { id: "a1", label: "Ask about pain onset and character", category: "Onset & Character", stage: "history", revealsClueIds: ["c1", "c3"], responseText: "It started about 45 minutes ago while I was mowing the lawn. It feels like heavy pressure right in the middle of my chest, and it's going down my left arm." },
      { id: "a2", label: "Ask about associated symptoms", category: "Associated Symptoms", stage: "history", revealsClueIds: ["c2"], responseText: "Yes, I'm sweating a lot and I feel really anxious. I also feel a bit nauseous." },
      { id: "a3", label: "Ask about past medical history", category: "Past History", stage: "history", revealsClueIds: ["c4"], responseText: "I have high blood pressure. I've been on medication for it but I haven't been great about taking it. I also smoke about a pack a day." },
      { id: "a4", label: "Ask about family history", category: "Family History", stage: "history", revealsClueIds: ["c8"], responseText: "My father had a heart attack when he was 55. His brother also had heart problems." },
      { id: "a5", label: "Vital signs", category: "Vitals", stage: "exam", revealsClueIds: ["c9", "c10"], responseText: "BP: 150/95 mmHg, HR: 105 bpm regular, RR: 20, SpO2: 96% on room air, Temp: 37.1°C" },
      { id: "a6", label: "Cardiovascular exam", category: "Cardiovascular", stage: "exam", revealsClueIds: ["c2"], responseText: "No murmurs or gallops. Lungs clear bilaterally. Mild diaphoresis noted. Patient appears anxious and uncomfortable." },
      { id: "a7", label: "12-lead ECG", category: "ECG", stage: "labs", revealsClueIds: ["c5"], responseText: "ST elevation in leads II, III, aVF. Reciprocal ST depression in leads I, aVL. Sinus tachycardia." },
      { id: "a8", label: "Troponin panel", category: "Labs", stage: "labs", revealsClueIds: ["c6"], responseText: "Troponin I: 2.4 ng/mL (normal < 0.04). CK-MB: 18 ng/mL (normal < 5)." },
      { id: "a9", label: "Chest X-ray", category: "Imaging", stage: "labs", revealsClueIds: ["c7"], responseText: "Chest X-ray: No acute findings. Heart size normal. No pulmonary edema. No pneumothorax." },
      { id: "a10", label: "Acute STEMI", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a11", label: "Unstable Angina", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a12", label: "Aortic Dissection", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a13", label: "Pulmonary Embolism", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a14", label: "GERD", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a15", label: "Aspirin 325mg", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a16", label: "Heparin bolus", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a17", label: "PCI consultation", category: "Interventions", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a18", label: "Nitroglycerin SL", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a19", label: "Morphine IV", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
    ],
    responseRules: [],
    scoringCriteria: [
      { id: "s1", name: "Reasoning Quality", description: "Did the user ask the right questions in a logical order?", maxPoints: 40 },
      { id: "s2", name: "Evidence Use", description: "Did the user order appropriate tests?", maxPoints: 30 },
      { id: "s3", name: "Efficiency", description: "Did the user reach a diagnosis without unnecessary steps?", maxPoints: 20 },
      { id: "s4", name: "Clinical Knowledge", description: "Was the correct diagnosis identified?", maxPoints: 10 },
    ],
    debriefTemplate: "This case demonstrated an acute STEMI presentation. The classic triad of crushing chest pain with radiation, diaphoresis, and ECG changes should immediately raise suspicion for acute coronary syndrome.",
    learningObjectives: [
      "Recognize the classic presentation of STEMI",
      "Understand the importance of rapid ECG acquisition in chest pain",
      "Know the initial management steps for STEMI",
      "Appreciate the role of risk factors in CAD",
    ],
  },
  {
    metadata: {
      id: "case-002",
      title: "Headache in a 28F",
      specialty: "Neurology",
      difficulty: "easy",
      estimatedMinutes: 10,
      tags: ["neurology", "headache", "migraine"],
    },
    presentingComplaint:
      "A 28-year-old female presents with a 3-day history of progressively worsening unilateral throbbing headache, photophobia, and nausea.",
    diagnosis: "Migraine with aura",
    clueTree: [
      { id: "c1", text: "Unilateral throbbing headache", category: "history", value: 9 },
      { id: "c2", text: "Photophobia and nausea", category: "history", value: 8 },
      { id: "c3", text: "Visual aura (zigzag lines) before headache", category: "history", value: 10 },
      { id: "c4", text: "Family history of migraines", category: "history", value: 6 },
      { id: "c5", text: "Normal neurological exam", category: "exam", value: 5 },
      { id: "c6", text: "Headache worsened by light and sound", category: "history", value: 7 },
      { id: "c7", text: "Prior similar episodes since age 16", category: "history", value: 7 },
      { id: "c8", text: "No fever, no neck stiffness", category: "exam", value: 4 },
    ],
    allowedActions: [
      { id: "a1", label: "Ask about headache character", category: "Character", stage: "history", revealsClueIds: ["c1"], responseText: "It's a throbbing pain, mostly on the right side of my head. It feels like someone is hammering inside my skull." },
      { id: "a2", label: "Ask about associated symptoms", category: "Associated", stage: "history", revealsClueIds: ["c2", "c6"], responseText: "The light really bothers me, and sounds are almost unbearable. I've been throwing up too. I had to call in sick to work." },
      { id: "a3", label: "Ask about visual symptoms", category: "Visual", stage: "history", revealsClueIds: ["c3"], responseText: "Before the headache started, I saw these zigzag lines in my vision for about 20 minutes. It happened on both sides. This happens sometimes before the really bad headaches." },
      { id: "a4", label: "Ask about family and prior history", category: "History", stage: "history", revealsClueIds: ["c4", "c7"], responseText: "My mom gets terrible migraines. I've had these since I was about 16, but this one feels worse than usual." },
      { id: "a5", label: "Neurological exam", category: "Neuro", stage: "exam", revealsClueIds: ["c5", "c8"], responseText: "Alert and oriented. PERRL, extraocular movements intact. No focal deficits. Fundoscopy normal. No meningeal signs. Neck supple." },
      { id: "a6", label: "Migraine with aura", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a7", label: "Tension headache", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a8", label: "Cluster headache", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a9", label: "Subarachnoid hemorrhage", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a10", label: "Sumatriptan 50mg PO", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a11", label: "Ibuprofen 600mg PO", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a12", label: "Dark room + rest", category: "Non-pharmacologic", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a13", label: "CT head without contrast", category: "Imaging", stage: "treatment", revealsClueIds: [], responseText: "" },
    ],
    responseRules: [],
    scoringCriteria: [
      { id: "s1", name: "Reasoning Quality", description: "Logical history-taking approach", maxPoints: 40 },
      { id: "s2", name: "Evidence Use", description: "Appropriate exam and investigation choices", maxPoints: 30 },
      { id: "s3", name: "Efficiency", description: "Reach diagnosis efficiently", maxPoints: 20 },
      { id: "s4", name: "Clinical Knowledge", description: "Correct diagnosis identified", maxPoints: 10 },
    ],
    debriefTemplate: "This was a classic migraine with aura. Key identifying features include unilateral throbbing pain, photophobia, nausea, visual aura, and family history.",
    learningObjectives: [
      "Distinguish migraine from other headache types",
      "Recognize the significance of visual aura",
      "Understand when headache requires urgent investigation vs. primary diagnosis",
    ],
  },
  {
    metadata: {
      id: "case-003",
      title: "Shortness of Breath in a 65M",
      specialty: "Pulmonology",
      difficulty: "hard",
      estimatedMinutes: 20,
      tags: ["respiratory", "COPD", "acute exacerbation"],
    },
    presentingComplaint:
      "A 65-year-old male with a known history of COPD presents with 2 days of worsening shortness of breath, increased sputum production, and change in sputum color from white to yellow-green.",
    diagnosis: "Acute exacerbation of COPD (AECOPD) with possible pneumonia",
    clueTree: [
      { id: "c1", text: "Worsening dyspnea over 2 days", category: "history", value: 8 },
      { id: "c2", text: "Increased sputum production with color change", category: "history", value: 9 },
      { id: "c3", text: "40 pack-year smoking history", category: "history", value: 7 },
      { id: "c4", text: "Known COPD diagnosis, last FEV1 45%", category: "history", value: 6 },
      { id: "c5", text: "Use of home O2, currently on 2L NC", category: "history", value: 5 },
      { id: "c6", text: "Wheezing and prolonged expiratory phase", category: "exam", value: 8 },
      { id: "c7", text: "SpO2 88% on 2L NC", category: "exam", value: 9 },
      { id: "c8", text: "Crackles at right lower lobe", category: "exam", value: 8 },
      { id: "c9", text: "Elevated WBC 14,000 with left shift", category: "labs", value: 7 },
      { id: "c10", text: "Chest X-ray: right lower lobe infiltrate", category: "labs", value: 10 },
      { id: "c11", text: "ABG: pH 7.32, PaCO2 52, PaO2 58", category: "labs", value: 9 },
      { id: "c12", text: "Not on antibiotics at home", category: "history", value: 4 },
    ],
    allowedActions: [
      { id: "a1", label: "Ask about symptom progression", category: "Progression", stage: "history", revealsClueIds: ["c1", "c2"], responseText: "It started 2 days ago. My breathing got worse and I'm producing a lot more sputum than usual. It went from white to this yellow-green color." },
      { id: "a2", label: "Ask about smoking history", category: "Social", stage: "history", revealsClueIds: ["c3"], responseText: "I smoked about 2 packs a day for 20 years. I quit 5 years ago but the damage is done." },
      { id: "a3", label: "Ask about COPD history", category: "Past History", stage: "history", revealsClueIds: ["c4", "c5", "c12"], responseText: "I was diagnosed with COPD about 8 years ago. My last breathing test showed my FEV1 was about 45% of what it should be. I use oxygen at home on 2 liters. I'm not on any antibiotics right now." },
      { id: "a4", label: "Respiratory exam", category: "Respiratory", stage: "exam", revealsClueIds: ["c6", "c7", "c8"], responseText: "Audible wheezing bilaterally. Prolonged expiratory phase. Decreased breath sounds at bases. Crackles heard at right lower lobe. SpO2: 88% on 2L nasal cannula." },
      { id: "a5", label: "CBC with differential", category: "Labs", stage: "labs", revealsClueIds: ["c9"], responseText: "WBC: 14,200/μL (normal 4,500-11,000). Neutrophils: 82%. Lymphocytes: 12%. Hemoglobin: 15.2 g/dL." },
      { id: "a6", label: "Chest X-ray", category: "Imaging", stage: "labs", revealsClueIds: ["c10"], responseText: "Right lower lobe airspace opacification consistent with pneumonia. Hyperinflation of lungs. Flattened diaphragms. No pleural effusion." },
      { id: "a7", label: "Arterial blood gas", category: "Labs", stage: "labs", revealsClueIds: ["c11"], responseText: "pH: 7.32 (low). PaCO2: 52 mmHg (high). PaO2: 58 mmHg (low). HCO3: 26 mEq/L. A-a gradient: elevated. Shows acute-on-chronic respiratory acidosis with hypoxemia." },
      { id: "a8", label: "AECOPD with pneumonia", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a9", label: "AECOPD without infection", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a10", label: "Pulmonary embolism", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a11", label: "Heart failure exacerbation", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a12", label: "Pneumothorax", category: "Diagnosis", stage: "diagnosis", revealsClueIds: [], responseText: "" },
      { id: "a13", label: "Bronchodilator nebulizer", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a14", label: "Systemic corticosteroids", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a15", label: "Antibiotics (community-acquired)", category: "Medications", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a16", label: "Supplemental oxygen to target SpO2 88-92%", category: "Supportive", stage: "treatment", revealsClueIds: [], responseText: "" },
      { id: "a17", label: "Non-invasive ventilation (BiPAP)", category: "Interventions", stage: "treatment", revealsClueIds: [], responseText: "" },
    ],
    responseRules: [],
    scoringCriteria: [
      { id: "s1", name: "Reasoning Quality", description: "Systematic approach to respiratory assessment", maxPoints: 40 },
      { id: "s2", name: "Evidence Use", description: "Appropriate test selection and interpretation", maxPoints: 30 },
      { id: "s3", name: "Efficiency", description: "Reach diagnosis without unnecessary tests", maxPoints: 20 },
      { id: "s4", name: "Clinical Knowledge", description: "Correct diagnosis and understanding of AECOPD", maxPoints: 10 },
    ],
    debriefTemplate: "This case illustrates an acute exacerbation of COPD triggered by pneumonia. The key findings are the triad of worsening dyspnea, increased sputum with purulence, and fever/crackles suggesting infection.",
    learningObjectives: [
      "Identify the cardinal features of AECOPD",
      "Understand the role of infection as an exacerbation trigger",
      "Interpret ABG in the context of chronic lung disease",
      "Know the initial management steps for AECOPD",
    ],
  },
];
